"""adding phone number

Revision ID: fb757c2a92c3
Revises: 04ce7a19ba65
Create Date: 2022-12-05 23:20:21.606989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb757c2a92c3'
down_revision = '04ce7a19ba65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
